import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "primereact/resources/themes/lara-light-indigo/theme.css"; // PrimeReact 테마
import "primereact/resources/primereact.min.css"; // PrimeReact 기본 스타일
import "primeicons/primeicons.css"; // PrimeIcons 스타일

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
